-- General options
require("options.vim")
require("options.theme")
require("options.keymap")

-- Plguin options
require("options.gitsigns")
require("options.lualine")
require("options.glow")
require("options.telescope")
require("options.nvimtree")
require("options.treesitter")
require("options.neodev")
require("options.lspconfig")
require("options.fidget")
require("options.luasnip")
require("options.mason")
require("options.cmp")
require("options.surround")
require("options.comment")
require("options.hop")
require("options.barbar")
require("options.toggleterm")
require("options.todocomments")
require("options.guessindent")
require("options.trouble")
require("options.cmaketools")
require("options.miniindentscope")
require("options.miniautopair")
require("options.notify")
require("options.dressing")


